### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by GamerMJay** [t-starks/MCPEDiscord#1]
Hello, I wanted to ask why you change the author and don't give credit to the original?
https://github.com/GamerMJay/MCPEToDiscord/

**Comment by GamerMJay** [comment]
@t-starks

**Comment by GamerMJay** [comment]
@t-starks

**Comment by GamerMJay** [comment]
@t-starks

**Comment by GamerMJay** [comment]
Why don't you answer? 🤔

**Comment by t-starks** [comment]
> Why don't you answer? 🤔

@GamerMJay 

Hello,

I wanted to apologize for not having responded sooner. I have been very busy with various school projects and other personal projects.

I understand your concern and want to clarify that it was not my intention to change the author of the plugin or take credit for someone else's work. I'm using the project as a guide to learn how to connect Discord and Minecraft PE so I can create my own Discord bot for my Minecraft server.

I really appreciate the work of GamerMJayy and the original developer. I will make sure to give proper credit and make any necessary edits so that it is clear that the work is yours and that I am only using it as a reference for my learning.

Thanks for pointing this out, and I'm sorry for any misunderstanding.

Greetings,

T. Stark
